### ISSUE TITLE
Process is immediately stopped by error

### ISSUE THREAD

**Issue by anthonyarutyunov** [samrandhaji/Undetectable-AI#2]
The process keeps stopping and returning this error

{'score': 0.8759689927101135, 'label': 'AI-Generated'}
{'score': 0.8759689927101135, 'label': 'AI-Generated'}
{'score': 0.9673469662666321, 'label': 'Human-Generated'}
{'score': 0.9372385144233704, 'label': 'Human-Generated'}
Traceback (most recent call last):
  File "C:\Users\Home\Downloads\Undetectable-AI-main\Undetectable-AI-main\main.py", line 271, in <module>
    process_docx(args.file_path, args.output_file_path, args.target_lang, args.grammar, args.chatgpt)
  File "C:\Users\Home\Downloads\Undetectable-AI-main\Undetectable-AI-main\main.py", line 216, in process_docx
    if(getScore(output_text)):
       ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Home\Downloads\Undetectable-AI-main\Undetectable-AI-main\main.py", line 147, in getScore
    score = resp['score']
            ~~~~^^^^^^^^^
KeyError: 'score'

**Comment by anthonyarutyunov** [comment]
I solved this myself by creating an account with Ollama and my own namespace, then I pulled my desired AI model to that name space and used the name provided on the instruction page when creating the namespace as the model name for the command,
