### ISSUE TITLE
no output

### ISSUE THREAD

**Issue by wi-wi** [samrandhaji/Undetectable-AI#4]
python main.py input.docx --output_file_path out.docx --model dolphin-mistral:latest --target_lang english --grammar off --chatgpt on
Traceback (most recent call last):
  File "main.py", line 271, in <module>
    process_docx(args.file_path, args.output_file_path, args.target_lang, args.grammar, args.chatgpt)
  File "main.py", line 216, in process_docx
    if(getScore(output_text)):
  File "main.py", line 147, in getScore
    score = resp['score']
KeyError: 'score'
--------------
no output. I placed input.docx in the same folder as main.py. inserted chatgt api key in main.py.

**Comment by wi-wi** [comment]
I tricked the script by setting function getScore to True and  isHuman(input_text) to return int(resp['data']['isAIgenerated']) ... no the output is stored but the contents has not been changed.
